export enum RouteNamesEnums {
  STORE = 'STORE',
  PRODUCTS = 'PRODUCTS',
  PRODUCT_ADD = 'PRODUCT_ADD',
  PRODUCT_EDIT = 'PRODUCT_EDIT',
  SECTIONS = 'SECTIONS',
  SECTION_ADD = 'SECTION_ADD',
  SECTION_EDIT = 'SECTION_EDIT',
  ORDERS = 'ORDERS',
}
